# Generated by Django 5.2.17 on 2026-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_id', models.IntegerField(db_index=True)),
                ('true_color_url', models.CharField(blank=True, max_length=500, null=True)),
                ('false_color_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ndvi_url', models.CharField(blank=True, max_length=500, null=True)),
                ('nbr_url', models.CharField(blank=True, max_length=500, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
