# Generated by Django 5.2.17 on 2026-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmsDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('acq_date', models.DateField()),
                ('acq_time', models.CharField(max_length=10)),
                ('frp', models.FloatField()),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('bright_ti4', models.FloatField(blank=True, null=True)),
                ('bright_ti5', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('satellite', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('daynight', models.CharField(blank=True, max_length=1, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firms_detections',
                'indexes': [models.Index(fields=['acq_date'], name='firms_detec_acq_dat_7c4200_idx'), models.Index(fields=['satellite', 'instrument'], name='firms_detec_satelli_7ad6e8_idx')],
            },
        ),
    ]
