# Generated by Django 5.2.17 on 2026-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('first_detected', models.DateTimeField()),
                ('last_detected', models.DateTimeField()),
                ('detection_count', models.IntegerField()),
                ('mean_frp', models.FloatField()),
                ('median_frp', models.FloatField()),
                ('max_frp', models.FloatField()),
                ('min_frp', models.FloatField()),
                ('frp_std', models.FloatField(blank=True, null=True)),
                ('persistence', models.FloatField()),
                ('classification', models.CharField(default='UNKNOWN', max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='NORMAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'thermal_sources',
            },
        ),
    ]
