# Generated by Django 5.2.17 on 2026-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='label_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='label_evidence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='label_sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='label_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
