# Generated by Django 5.2.17 on 2026-09-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_hotspot_label_hotspot_label_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='missing_sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EnrichmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('query_timestamp', models.DateTimeField()),
                ('available', models.BooleanField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspots.hotspot')),
            ],
        ),
    ]
