# Generated by Django 5.2.17 on 2026-09-12 09:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_hotspot_features_hotspot_latitude_hotspot_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('distance_km', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCoverTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.CharField(blank=True, max_length=50, null=True)),
                ('land_cover_class', models.CharField(blank=True, max_length=100, null=True)),
                ('tree_cover', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotspot',
            name='decision_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='industrial_subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='landcover_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='landcover_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='osm_query_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='population_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='source_context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='thermal_behaviour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='weather_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EnrichmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_statuses', to='hotspots.hotspot')),
            ],
        ),
        migrations.AddField(
            model_name='hotspot',
            name='enrichment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotspots.enrichmentstatus'),
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence_text', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='hotspots.hotspot')),
            ],
        ),
        migrations.AddField(
            model_name='hotspot',
            name='evidence_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotspots.evidencerecord'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='facility_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspots.facilitycandidate'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspots.modelversion'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='world_cover_tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspots.worldcovertile'),
        ),
    ]
