# Generated by Django 5.2.17 on 2026-09-13 07:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0004_facilitycandidate_modelversion_worldcovertile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
