# Generated by Django 5.2.17 on 2026-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0005_hotspot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='bright_t31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='bright_ti4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='bright_ti5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='daynight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='industrial_anomaly_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending enrichment'), ('PARTIAL', 'Partial evidence'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed processing')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='satellite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='track',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='scan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
