# Generated by Django 5.2.17 on 2026-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0007_indiaboundary_alter_facilitycandidate_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='confidence_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='label_confidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
