# Generated by Django 5.2.17 on 2026-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0008_alter_hotspot_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='attribution_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='cropland_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='evidence_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='footprint_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='grass_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='is_tentative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='other_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='shrub_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='tree_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='valid_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
