import { useState, useEffect } from 'react';
import { ThermalEvent, Metadata } from '../../types';
import { AIAnalysis } from './tabs/AIAnalysis';
import { ImpactAssessment } from './tabs/ImpactAssessment';
import { Advisory } from './tabs/Advisory';
import { Telemetry } from './tabs/Telemetry';

interface EventDossierProps {
  selectedEvent: ThermalEvent | null;
  isOpen: boolean;
  onClose: () => void;
  metadata?: Metadata | null;
  activeTab?: 'ai' | 'impact' | 'advisory' | 'telemetry';
  onTabChange?: (tab: 'ai' | 'impact' | 'advisory' | 'telemetry') => void;
}

export function EventDossier({
  selectedEvent,
  isOpen,
  onClose,
  metadata,
  activeTab: controlledActiveTab,
  onTabChange
}: EventDossierProps) {
  const [internalTab, setInternalTab] = useState<'ai' | 'impact' | 'advisory' | 'telemetry'>('ai');
  const [alertModalOpen, setAlertModalOpen] = useState(false);
  const [copiedToast, setCopiedToast] = useState(false);

  const activeTab = controlledActiveTab !== undefined ? controlledActiveTab : internalTab;
  const setActiveTab = (tab: 'ai' | 'impact' | 'advisory' | 'telemetry') => {
    if (onTabChange) {
      onTabChange(tab);
    } else {
      setInternalTab(tab);
    }
  };

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (alertModalOpen) {
          setAlertModalOpen(false);
        } else if (isOpen) {
          onClose();
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, alertModalOpen, onClose]);

  const getIcon = (type: string) => {
    const icons: { [k: string]: string } = {
      'Wildfire': '🔥', 'Industrial Fire': '🏭', 'Gas Flare': '🛢️',
      'Agriculture Burning': '🌾', 'Mining Activity': '⛏️',
    };
    return icons[type] || '📍';
  };

  const handleCopyCoords = () => {
    if (!selectedEvent) return;
    const text = `${selectedEvent.lat.toFixed(5)}, ${selectedEvent.lng.toFixed(5)}`;
    navigator.clipboard.writeText(text);
    setCopiedToast(true);
    setTimeout(() => setCopiedToast(false), 2000);
  };

  const handleDownloadDossier = () => {
    if (!selectedEvent) return;
    const content = `=====================================================
THERMAL SENTINEL — SITUATIONAL INTELLIGENCE BRIEFING
NASA FIRMS Enhanced AI Thermal Anomaly Report
=====================================================

EVENT ID:         ${selectedEvent.id}
CLASSIFICATION:   ${selectedEvent.type}
RISK LEVEL:       ${selectedEvent.risk_score} (Composite Risk: ${selectedEvent.composite_risk}/100)
AI CONFIDENCE:    ${selectedEvent.confidence}%
LOCATION:         ${selectedEvent.lat.toFixed(5)}°N, ${selectedEvent.lng.toFixed(5)}°E
ZONE TYPE:        ${selectedEvent.impact?.zone_type || 'N/A'}
FRP (MW):         ${selectedEvent.frp} MW
PERSISTENCE:      ${selectedEvent.persistence_days} days
DETECTION AGE:    ${selectedEvent.detection_age_days} days

-----------------------------------------------------
1. AI SITUATION REPORT & RECOMMENDATION
-----------------------------------------------------
${selectedEvent.advisory?.situation_report || 'No active situation report recorded.'}

AI RECOMMENDATION (${selectedEvent.advisory?.ai_recommendation?.urgency || 'STANDARD'}):
${selectedEvent.advisory?.ai_recommendation?.recommendation || 'Standard monitoring recommended.'}
Confidence Note: ${selectedEvent.advisory?.ai_recommendation?.confidence_note || 'N/A'}

-----------------------------------------------------
2. POPULATION EXPOSURE & IMPACT ASSESSMENT
-----------------------------------------------------
Total Exposed Population: ${selectedEvent.impact?.total_population?.toLocaleString() || '0'}
Children at Risk:         ${selectedEvent.impact?.children_at_risk?.toLocaleString() || '0'}
Elderly at Risk:          ${selectedEvent.impact?.elderly_at_risk?.toLocaleString() || '0'}
Hazard Danger Area:       ${selectedEvent.impact?.danger_area_sq_km || 0} sq. km
Estimated Economic Impact: ₹${selectedEvent.impact?.economic_damage_crore || 0} Crore
Air Quality:              ${selectedEvent.impact?.aqi_category || 'N/A'} (PM2.5: ${selectedEvent.impact?.peak_pm25 || 0} ug/m3)
Health Advisory:          ${selectedEvent.impact?.health_advisory || 'N/A'}

-----------------------------------------------------
3. PUBLIC ADVISORY & EMERGENCY SMS
-----------------------------------------------------
English Advisory:
${selectedEvent.advisory?.public_advisory_en || 'N/A'}

Hindi Advisory:
${selectedEvent.advisory?.public_advisory_hi || 'N/A'}

Emergency SMS Broadcast:
${selectedEvent.advisory?.sms_alert || 'N/A'}

=====================================================
GENERATED BY THERMAL SENTINEL v3.2 — ${new Date().toISOString()}
=====================================================
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dossier_${selectedEvent.id}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      {/* Backdrop overlay for outside click to close */}
      <div
        className={`drawer-backdrop ${isOpen ? 'open' : ''}`}
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Slide-in Drawer */}
      <aside className={`dossier-drawer ${isOpen ? 'open' : ''}`} aria-label="Event Intelligence Dossier">
        {selectedEvent ? (
          <div className="dossier-inner">
            <div className="dossier-header-panel">
              <div className="dossier-header-top">
                <div className="dossier-title-area">
                  <span className="dossier-icon">{getIcon(selectedEvent.type)}</span>
                  <div className="dossier-title-text">
                    <div className="dossier-id-row">
                      <h3>{selectedEvent.id}</h3>
                      <span className="dossier-sensor-badge">VIIRS 375m</span>
                    </div>
                    <span className="dossier-type-badge" style={{ color: selectedEvent.color }}>
                      {selectedEvent.type}
                    </span>
                  </div>
                </div>

                <div className="dossier-header-actions">
                  <span className={`composite-badge risk-bg-${selectedEvent.risk_score?.toLowerCase()}`}>
                    {selectedEvent.risk_score} {selectedEvent.composite_risk}/100
                  </span>
                  <button
                    className="drawer-close-btn"
                    onClick={onClose}
                    title="Close Dossier (Esc)"
                    aria-label="Close"
                  >
                    ✕
                  </button>
                </div>
              </div>

              {/* Action Toolbar in Dossier Header */}
              <div className="dossier-quick-toolbar">
                <button className="dossier-action-chip" onClick={handleCopyCoords} title="Copy Coordinates">
                  <span>📍</span>
                  <span>{copiedToast ? 'Copied!' : `${selectedEvent.lat.toFixed(3)}°N, ${selectedEvent.lng.toFixed(3)}°E`}</span>
                </button>
                <button className="dossier-action-chip" onClick={handleDownloadDossier} title="Download Briefing Report">
                  <span>📄</span>
                  <span>Export Briefing</span>
                </button>
                <div className="meta-pill">
                  <span className="meta-k">FRP:</span>
                  <span className="meta-v frp-highlight">{selectedEvent.frp} MW</span>
                </div>
                <div className="meta-pill">
                  <span className="meta-k">Age:</span>
                  <span className="meta-v">{selectedEvent.detection_age_days <= 1 ? '<24h' : `${selectedEvent.detection_age_days}d`}</span>
                </div>
              </div>

              <div className="ai-confidence">
                <div className="conf-header">
                  <span>AI Ensemble Confidence (8 Methods)</span>
                  <span className="conf-value">{selectedEvent.confidence}%</span>
                </div>
                <div className="progress-bar">
                  <div
                    className="fill"
                    style={{ width: `${selectedEvent.confidence}%`, backgroundColor: selectedEvent.color }}
                  ></div>
                </div>
              </div>

              <nav className="tab-nav" role="tablist">
                {(['ai', 'impact', 'advisory', 'telemetry'] as const).map(tab => (
                  <button
                    key={tab}
                    role="tab"
                    aria-selected={activeTab === tab}
                    className={`tab-btn ${activeTab === tab ? 'active' : ''}`}
                    onClick={() => setActiveTab(tab)}
                  >
                    {tab === 'ai' && '🤖 AI Analysis'}
                    {tab === 'impact' && '⚠️ Impact'}
                    {tab === 'advisory' && '📋 Advisory'}
                    {tab === 'telemetry' && '🛰️ Telemetry'}
                  </button>
                ))}
              </nav>
            </div>

            <div className="dossier-body">
              {activeTab === 'ai' && <AIAnalysis event={selectedEvent} />}
              {activeTab === 'impact' && (
                <ImpactAssessment event={selectedEvent} setAlertModalOpen={setAlertModalOpen} />
              )}
              {activeTab === 'advisory' && <Advisory event={selectedEvent} />}
              {activeTab === 'telemetry' && <Telemetry event={selectedEvent} metadata={metadata} />}
            </div>
          </div>
        ) : (
          <div className="drawer-empty-state">
            <span style={{ fontSize: '48px', opacity: 0.4 }}>📍</span>
            <h4>No Anomaly Selected</h4>
            <p>Select any thermal anomaly on the map or from the mission list to view the AI Dossier & Impact Assessment.</p>
            <button className="empty-state-close-btn" onClick={onClose}>Close Drawer</button>
          </div>
        )}
      </aside>

      {/* Alert Modal */}
      {alertModalOpen && selectedEvent && (
        <div className="modal-overlay" onClick={() => setAlertModalOpen(false)}>
          <div className="modal-content" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>🚨 Multi-Channel Emergency Alert System</h3>
              <button className="modal-x-btn" onClick={() => setAlertModalOpen(false)}>✕</button>
            </div>
            <p>Dispatching immediate public and agency advisories for <strong>{selectedEvent.id}</strong> ({selectedEvent.type})</p>
            
            <div className="alert-channels">
              <button className="channel-btn channel-sms">
                <span>📱</span>
                <div>
                  <strong>Emergency SMS Broadcast</strong>
                  <span className="channel-sub">Targeting {selectedEvent.impact?.total_population?.toLocaleString() || 'active zone'} residents</span>
                </div>
              </button>
              <button className="channel-btn channel-siren">
                <span>🔊</span>
                <div>
                  <strong>Acoustic Early-Warning Sirens</strong>
                  <span className="channel-sub">Activate acoustic alarms in {selectedEvent.toxic_radius_km} km radius</span>
                </div>
              </button>
              <button className="channel-btn channel-social">
                <span>📣</span>
                <div>
                  <strong>Official Social & Media Wire</strong>
                  <span className="channel-sub">Publish verified situation warnings to public feeds</span>
                </div>
              </button>
              <button className="channel-btn channel-pa">
                <span>📡</span>
                <div>
                  <strong>Public Address (PA) Broadcast</strong>
                  <span className="channel-sub">Audio warnings via local municipal towers</span>
                </div>
              </button>
              <button className="channel-btn channel-ndrf">
                <span>🚒</span>
                <div>
                  <strong>NDRF & SDRF First Responder Dispatch</strong>
                  <span className="channel-sub">Priority alert to emergency response units</span>
                </div>
              </button>
            </div>

            {selectedEvent.advisory?.sms_alert && (
              <div className="modal-sms-preview">
                <h5>SMS Broadcast Dispatch Text:</h5>
                <p>{selectedEvent.advisory.sms_alert}</p>
              </div>
            )}

            <button className="modal-close" onClick={() => setAlertModalOpen(false)}>
              Dismiss & Return to Command Center
            </button>
          </div>
        </div>
      )}
    </>
  );
}
